"""Add analytics columns to SearchHistory

Revision ID: 597989eaa33f
Revises: 0001_initial_schema
Create Date: 2026-07-16 11:40:20.112945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '597989eaa33f'
down_revision: Union[str, None] = '0001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_history', sa.Column('ai_answer', sa.Text(), nullable=True))
    op.add_column('search_history', sa.Column('knowledge_source', sa.String(length=100), nullable=True))
    op.add_column('search_history', sa.Column('source_documents', sqlite.JSON(), nullable=True))
    op.add_column('search_history', sa.Column('response_time_ms', sa.Integer(), nullable=True))
    op.add_column('search_history', sa.Column('embedding_time_ms', sa.Integer(), nullable=True))
    op.add_column('search_history', sa.Column('retrieval_time_ms', sa.Integer(), nullable=True))
    op.add_column('search_history', sa.Column('generation_time_ms', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_history', 'generation_time_ms')
    op.drop_column('search_history', 'retrieval_time_ms')
    op.drop_column('search_history', 'embedding_time_ms')
    op.drop_column('search_history', 'response_time_ms')
    op.drop_column('search_history', 'source_documents')
    op.drop_column('search_history', 'knowledge_source')
    op.drop_column('search_history', 'ai_answer')
    # ### end Alembic commands ###
